In [25]:
from sklearn.decomposition import PCA
import copy
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

In [1]:
v1 = [0.49, 0.44, 0.50, 0.35,
      0.26, 0.41, 0.34, 0.28,
      0.20, 0.45, 0.48, 0.46,
      0.44, 0.51, 0.42, 0.36]
v2 = [0.2700, 0.0700, 0.2300, 0.3600,
      0.3600, 0.1300, 0.3000, 0.3800,
      0.2800, 0.2800, 0.2300, 0.5400,
      0.1200, 0.2400, 0.2400, 0.3300]
v3 = [0.5500, 0.5000, 0.5100, 0.5800,
      0.6100, 0.5100, 0.6200, 0.3800,
      0.7200, 0.5800, 0.7300, 0.5200,
      0.6100, 0.5800, 0.5700, 0.4600]
v4 = [0.29, 0.43, 0.24, 0.25,
      0.26, 0.54, 0.47, 0.38,
      0.47, 0.44, 0.61, 0.35,
      0.32, 0.49, 0.45, 0.44]
v5 = [0.6900, 0.7700, 0.9000, 0.7700,
      0.8100, 0.9200, 0.8900, 0.7100,
      1.0000, 0.9200, 0.7600, 0.8600,
      0.7300, 0.8500, 0.8400, 0.8100]
v6 = [0.7800, 0.8500, 0.6700, 0.6700,
      0.5700, 0.8400, 0.7700, 0.6500,
      0.6700, 0.7000, 0.8900, 0.7700,
      0.7300, 0.7900, 0.7200, 0.8300]
v7 = [0.3000, 0.2200, 0.3400, 0.3100,
      0.3400, 0.2800, 0.3500, 0.3200,
      0.4100, 0.2800, 0.3100, 0.1600,
      0.3200, 0.3900, 0.2600, 0.3200]
v8 = [0.5600, 0.5900, 0.6800, 0.5900,
      0.6500, 0.5700, 0.6800, 0.5200,
      0.7500, 0.6800, 0.4500, 0.5300,
      0.7800, 0.6500, 0.6500, 0.7300]
v9 = [0.7500, 0.6700, 0.7500, 0.7600,
      0.6000, 0.7000, 0.7400, 0.8700,
      0.8100, 0.7500, 0.6500, 0.7600,
      0.8800, 0.8200, 0.6800, 0.5800]
v10 = [0.5200, 0.6000, 0.6100, 0.6400,
       0.4800, 0.6300, 0.6500, 0.4800,
       0.6200, 0.5100, 0.5000, 0.6000,
       0.8000, 0.7700, 0.6900, 0.5500]
v11 = [0.7800, 0.8200, 0.8800, 0.7800,
       0.8300, 0.8300, 0.9400, 0.7800,
       0.9000, 0.8100, 0.7500, 0.7100,
       0.8400, 0.7200, 0.9900, 0.7200]
v12 = [0.7000, 0.8900, 0.8400, 0.8800,
       0.8400, 0.9300, 0.8700, 0.7900,
       0.9600, 0.5500, 0.6700, 0.8600,
       0.8500, 0.7800, 0.7000, 0.7000]
v13 = [0.3100, 0.1200, 0.3500, 0.0700,
       0.2400, 0.2700, 0.4000, 0.2400,
       0.2800, 0.3700, 0.4100, 0.3900,
       0.2900, 0.2400, 0.3800, 0.3400]
v14 = [0.6400, 0.6500, 0.7400, 0.8200,
       0.8800, 0.6700, 0.9300, 0.9200,
       0.9200, 0.6500, 0.6500, 0.7200,
       0.9600, 0.8000, 0.6300, 0.6700]
v15 = [0.4400, 0.3400, 0.4300, 0.3100,
       0.4400, 0.4900, 0.3300, 0.4200,
       0.3600, 0.2100, 0.4500, 0.3700,
       0.3400, 0.3800, 0.3900, 0.3600]
v16 = [0.6900, 0.5600, 0.7200, 0.6400,
       0.6400, 0.5500, 0.6800, 0.9500,
       0.6900, 0.6800, 0.6300, 0.5900,
       0.6500, 0.5300, 0.6000, 0.4400]
v17 = [0.3500, 0.4600, 0.2000, 0.3000,
       0.3600, 0.4100, 0.6600, 0.2900,
       0.3500, 0.2500, 0.5000, 0.4500,
       0.5200, 0.2400, 0.4300, 0.5600]
v18 = [0.7900, 0.6600, 0.4200, 0.5700,
       0.6600, 0.6300, 0.5600, 0.7800,
       0.5400, 0.5200, 0.4900, 0.7500,
       0.8600, 0.4900, 0.6600, 0.6200]
v19 = [0.7400, 0.6100, 0.7100, 0.7000,
       0.6900, 0.6700, 0.7200, 0.7500,
       0.6800, 0.6200, 0.6800, 0.8300,
       0.6800, 0.6600, 0.6800, 0.7600]
v20 = [0.5700, 0.5300, 0.5200, 0.6400,
       0.7200, 0.5600, 0.4900, 0.5600,
       0.4900, 0.5300, 0.6600, 0.6300,
       0.6700, 0.6600, 0.5600, 0.3400]

In [16]:
data = [v1, v2, v3, v4, v5, v6, v7, v8, v9, v10,
        v11, v12, v13, v14, v15, v16, v17, v18, v19, v20]
print(np.array(data))

[[0.49 0.44 0.5  0.35 0.26 0.41 0.34 0.28 0.2  0.45 0.48 0.46 0.44 0.51
  0.42 0.36]
 [0.27 0.07 0.23 0.36 0.36 0.13 0.3  0.38 0.28 0.28 0.23 0.54 0.12 0.24
  0.24 0.33]
 [0.55 0.5  0.51 0.58 0.61 0.51 0.62 0.38 0.72 0.58 0.73 0.52 0.61 0.58
  0.57 0.46]
 [0.29 0.43 0.24 0.25 0.26 0.54 0.47 0.38 0.47 0.44 0.61 0.35 0.32 0.49
  0.45 0.44]
 [0.69 0.77 0.9  0.77 0.81 0.92 0.89 0.71 1.   0.92 0.76 0.86 0.73 0.85
  0.84 0.81]
 [0.78 0.85 0.67 0.67 0.57 0.84 0.77 0.65 0.67 0.7  0.89 0.77 0.73 0.79
  0.72 0.83]
 [0.3  0.22 0.34 0.31 0.34 0.28 0.35 0.32 0.41 0.28 0.31 0.16 0.32 0.39
  0.26 0.32]
 [0.56 0.59 0.68 0.59 0.65 0.57 0.68 0.52 0.75 0.68 0.45 0.53 0.78 0.65
  0.65 0.73]
 [0.75 0.67 0.75 0.76 0.6  0.7  0.74 0.87 0.81 0.75 0.65 0.76 0.88 0.82
  0.68 0.58]
 [0.52 0.6  0.61 0.64 0.48 0.63 0.65 0.48 0.62 0.51 0.5  0.6  0.8  0.77
  0.69 0.55]
 [0.78 0.82 0.88 0.78 0.83 0.83 0.94 0.78 0.9  0.81 0.75 0.71 0.84 0.72
  0.99 0.72]
 [0.7  0.89 0.84 0.88 0.84 0.93 0.87 0.79 0.96 0.55 0.67 0.86 0.8

In [17]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler() #实例化
scaler = scaler.fit(np.array(data)) #fit，在这里本质是生成min(x)和max(x)
MinMaxScaler_features = scaler.transform(np.array(data)) #通过接口导出结果

MinMaxScaler_features

array([[0.42307692, 0.45121951, 0.42857143, 0.34567901, 0.03125   ,
        0.35      , 0.0625    , 0.05633803, 0.        , 0.33802817,
        0.37878788, 0.42857143, 0.38095238, 0.44262295, 0.24      ,
        0.07843137],
       [0.        , 0.        , 0.04285714, 0.35802469, 0.1875    ,
        0.        , 0.        , 0.1971831 , 0.1       , 0.09859155,
        0.        , 0.54285714, 0.        , 0.        , 0.        ,
        0.01960784],
       [0.53846154, 0.52439024, 0.44285714, 0.62962963, 0.578125  ,
        0.475     , 0.5       , 0.1971831 , 0.65      , 0.52112676,
        0.75757576, 0.51428571, 0.58333333, 0.55737705, 0.44      ,
        0.2745098 ],
       [0.03846154, 0.43902439, 0.05714286, 0.22222222, 0.03125   ,
        0.5125    , 0.265625  , 0.1971831 , 0.3375    , 0.32394366,
        0.57575758, 0.27142857, 0.23809524, 0.40983607, 0.28      ,
        0.23529412],
       [0.80769231, 0.85365854, 1.        , 0.86419753, 0.890625  ,
        0.9875    , 0.921875  , 

In [18]:
MinMaxScaler_features.shape

(20, 16)

In [29]:
result = []
for coef in range(2,7):
    print("-"*70)
    print(f"n_clusters = {coef}")
    kmeans = KMeans(n_clusters=coef,random_state=10).fit(MinMaxScaler_features)
    print(kmeans.labels_)
    result.append(kmeans.labels_)

----------------------------------------------------------------------
n_clusters = 2
[0 0 1 0 1 1 0 1 1 1 1 1 0 1 0 1 0 1 1 1]
----------------------------------------------------------------------
n_clusters = 3
[1 1 0 1 2 2 1 0 2 0 2 2 1 2 1 0 1 0 2 0]
----------------------------------------------------------------------
n_clusters = 4
[0 3 2 0 1 1 3 2 1 2 1 1 3 1 0 2 0 2 1 2]
----------------------------------------------------------------------
n_clusters = 5
[1 4 0 1 3 2 4 0 2 0 3 3 4 3 1 0 1 0 2 0]
----------------------------------------------------------------------
n_clusters = 6
[4 0 5 4 2 2 0 3 1 3 2 2 0 2 4 1 4 1 3 5]


In [33]:
df = pd.DataFrame(result, index=[f"聚{idx}类" for idx in range(2, 7)], columns=[f"v{idx}" for idx in range(1, 21)])
df.to_csv("./result.csv", encoding="utf-8-sig")
df

v1  v2  v3  v4  v5  v6  v7  v8  v9  v10  v11  v12  v13  v14  v15  v16  \
聚2类   0   0   1   0   1   1   0   1   1    1    1    1    0    1    0    1   
聚3类   1   1   0   1   2   2   1   0   2    0    2    2    1    2    1    0   
聚4类   0   3   2   0   1   1   3   2   1    2    1    1    3    1    0    2   
聚5类   1   4   0   1   3   2   4   0   2    0    3    3    4    3    1    0   
聚6类   4   0   5   4   2   2   0   3   1    3    2    2    0    2    4    1   

     v17  v18  v19  v20  
聚2类    0    1    1    1  
聚3类    1    0    2    0  
聚4类    0    2    1    2  
聚5类    1    0    2    0  
聚6类    4    1    3    5